project3
Danilka776/backend-java pull request #8
Opened 2023-11-19 14:01 UTC by Danilka776

2024-01-07 20:19 UTC, strelchm requested changes

2024-01-07 20:19 UTC, strelchm commented on src/main/java/edu/project3/LogReport.java
> +    public String toMarkdown() {
Методы можно вынести в отдельные классы. Например, StatisticsWriter интерфейс и реализации MDStatisticsWriter и ADocStatisticsWriter. Это будет особенно актуально при масштабировании, когда количество способов записей будет увеличиваться (в текущей реализации будут добавляться новые методы, будет 1000+ строк и разобраться будет очень трудно, + разные доп трудности)
[См. про SOLID](https://www.baeldung.com/solid-principles)

2024-01-07 20:19 UTC, strelchm commented on src/main/java/edu/project3/LogAnalyzer.java
> +package edu.project3;
В одном классе много функций, здесь и парсинг файла и подсчет статистики (причем разные методы) и генерация отчета. Необходимо разделить по разным классам / интерфейсам. Классы должны соответствовать **single responsibility** - один класс отвечает за одну функциональность, в противном случае масштабирование приложения принесет проблемы с поддержкой кода
Детальнее [см. про SOLID](https://www.baeldung.com/solid-principles)

2024-01-07 20:19 UTC, strelchm commented on src/main/java/edu/project3/LogRecord.java
> +public class LogRecord {
**not important**: можно заюзать **record**, что бы убрать лишний код конструкторов-сеттеров-геттеров

2024-01-07 20:19 UTC, strelchm commented on src/main/java/edu/project3/LogAnalyzer.java
> +    private static void analyzeLocalLog(String path, LocalDate fromDate, LocalDate toDate, String format)
В методах **analyzeLocalLog** и **analyzeRemoteLog** много общего, по крайней мере кусок кода
```
        if (format.equalsIgnoreCase("markdown")) {
            System.out.println(logReport.toMarkdown());
        } else if (format.equalsIgnoreCase("adoc")) {
            System.out.println(logReport.toADoc());
        } else {
            System.out.println("Неподдерживаемый формат вывода. Используйте 'markdown' или 'adoc'.");
        }
```
Дублирование кода ведет к проблемам - при правках поправишь в одном месте, а в другом забудешь и это чревато багами. Необходимо подумать над тем, как код вынести в единое место, например это может быть абстрактный класс. SOLID принципы, упомянутые в других комментариях, помогут сделать это оптимально

2024-01-07 20:19 UTC, strelchm commented on src/main/java/edu/project3/LogAnalyzer.java
> +    private static void analyzeLocalLog(String path, LocalDate fromDate, LocalDate toDate, String format)
Тоже дублирование видно в функциях **parseDate** и **parseLogDate**

2024-01-07 20:19 UTC, strelchm commented on src/main/java/edu/project3/LogAnalyzer.java
> +            System.out.println(logReport.toMarkdown());
По заданию необходимо в отдельный файл сохранять результат-статистику

2024-01-09 20:35 UTC, Danilka776 commented on src/main/java/edu/project3/LogReport.java
> +    public String toMarkdown() {
Done

2024-01-10 08:17 UTC, Danilka776 commented on src/main/java/edu/project3/LogAnalyzer.java
> +package edu.project3;
Fixed

2024-01-10 08:30 UTC, Danilka776 commented on src/main/java/edu/project3/LogAnalyzer.java
> +    private static void analyzeLocalLog(String path, LocalDate fromDate, LocalDate toDate, String format)
Fixed

2024-01-10 08:48 UTC, Danilka776 commented on src/main/java/edu/project3/LogAnalyzer.java
> +            System.out.println(logReport.toMarkdown());
Done

2024-01-10 20:07 UTC, strelchm approved these changes

2024-01-11 08:07 UTC, merged